### PR TITLE
Intmat to jl array

### PR DESCRIPTION
**Pull request by ederc**
Fixes conversion from Singular intmat to Julia matrix.

### CODE REVIEW

**Review by hannes14 — APPROVED** [review]

**Comment by thofma** [comment]
Test is failing

**Comment by ederc** [comment]
Are the tests run with my changes in caller.cpp? This seems not to be the case. How can I trigger this?

**Comment by fingolfin** [comment]
This is currently not possible, but that's why I am working on PR #639

**Comment by ederc** [comment]
Yes.

**Pull request merged**
