### PR TITLE
hilbert series for smodule

### PR DESCRIPTION
**Pull request by hannes14**

### CODE REVIEW

**Review by fingolfin — APPROVED** [review]
Tests here pass -> good.

This is a new function, so I don't think it can break anything in Oscar, so I don't see a point in waiting for OscarCI.

**Comment by thofma** [comment]
Famous last words

**Comment by fingolfin** [comment]
OK, so I am waiting after all to make @thofma happy ;-), but I want to get some tests in soon, so I just released Singular.jl 0.18.4 anyway, and I am happy to release 0.18.5 later today

**Comment by thofma** [comment]
Sorry, I forgot to add a smiley.

**Pull request merged**
