### PR TITLE
Deprecate coeffs

### PR DESCRIPTION
**Pull request by wbhart**
This is the Singular equivalent of https://github.com/Nemocas/AbstractAlgebra.jl/pull/805

Of course this will fail until the new version of AbstractAlgebra is released.

This may be breaking for Oscar.

### CODE REVIEW

**Comment by tthsqe12** [comment]
This is fine. It is always hard to guess what everyone's favorite abbr is. How about a decision on the noun vs verb thing, i.e. factor vs factorize? This might be hard because there are names that are nouns that cannot be verbified, and there are names that are verbs that cannot be nounified.

**Comment by wbhart** [comment]
I don't think we can be consistent on that, but as far as I know the verb form is preferred.

**Comment by thofma** [comment]
Bumped the version, but it is failing.

**Comment by wbhart** [comment]
Just an import problem I think. Let's see if this works now.

**Comment by wbhart** [comment]
That is not good news. :-(

I have a spelling error in AbstractAlgebra. I've made a PR to fix it. Sorry!

**Comment by wbhart** [comment]
I guess this is where our new CI will really help us out when it is done!

**Comment by thofma** [comment]
We should have waited for the 81 jobs. One of them would have told us, see also https://github.com/oscar-system/OscarDevTools.jl/issues/9.

**Comment by wbhart** [comment]
Yeah, but 80 of them would have failed for some other reason. :-)

Looks good now though. Yay!

**Pull request merged**
