### PR TITLE
Update to 0.23.9

### PR DESCRIPTION
**Pull request by hannes14**
quotient /saturation for smodule
@wdecker 
@fingolfin 
function quotient(I::smodule{spoly{T}}, J::sideal{spoly{T}}) where T <: Nemo.FieldElem
function saturation(I::smodule{spoly{T}}, J::sideal{spoly{T}}) where T <: Nemo.FieldElem
function saturation2(I::smodule{spoly{T}}, J::sideal{spoly{T}}) where T <: Nemo.FieldElem

### CODE REVIEW

**Comment by wdecker** [comment]
@hannes14 Are there also

function quotient(I::smodule{spoly{T}}, J::smodule{spoly{T}}) where T <: Nemo.FieldElem

function saturation(I::smodule{spoly{T}}, J::smodule{spoly{T}}) where T <: Nemo.FieldElem

function saturation2(I::smodule{spoly{T}}, J::smodule{spoly{T}}) where T <: Nemo.FieldElem

These are the ones I need most.

**Comment by hannes14** [comment]
it has also
function quotient(I::smodule{spoly{T}}, J::smodule{spoly{T}}) where T <: Nemo.FieldElem

**Comment by wdecker** [comment]
Good! So let is proceed here and do saturation seperately!Von meinem iPhone gesendetAm 11.10.2024 um 15:46 schrieb Hans Schoenemann ***@***.***>:﻿
it has also
function quotient(I::smodule{spoly{T}}, J::smodule{spoly{T}}) where T <: Nemo.FieldElem

**Review by wdecker — APPROVED** [review]

**Comment by fingolfin** [comment]
@hannes14 after merging, you also need to trigger the release by going to the merged commit and commenting on it -- I just did it for you this time, see https://github.com/oscar-system/Singular.jl/commit/e3353c546b61e51b8aafee2c2490c539e22546a1

**Comment by wdecker** [comment]
@fingolfin Is there anything more to do here so that I can make use of it?

**Comment by fingolfin** [comment]
You should be able to make use of it already. It worked for me 15 minutes after my comment

**Comment by wdecker** [comment]
After updates, I still get this:

julia> methods(Singular.quotient)
# 2 methods for generic function "quotient" from Singular:
 [1] quotient(I::Singular.sideal{S}, J::Singular.sideal{S}) where S<:Singular.spluralg
     @ ~/.julia/packages/Singular/a0LzT/src/ideal/ideal.jl:569
 [2] quotient(I::Singular.sideal{S}, J::Singular.sideal{S}) where S<:Singular.spoly
     @ ~/.julia/packages/Singular/a0LzT/src/ideal/ideal.jl:557

So the methods for smodules are not there ...

**Pull request merged**
