### PR TITLE
Added permute_variables function

### PR DESCRIPTION
**Pull request by sebasguts**

### CODE REVIEW

**Comment by wbhart** [comment]
Spaces missing after commas in the test code.

This looks like another special case of evaluation. On the other hand, it can be done more efficiently. So maybe this is a candidate for a function in MPoly too.

**Comment by wbhart** [comment]
The test code fails. Presumably because you didn't export the function.

**Comment by wbhart** [comment]
@sebasguts See previous comments.

**Comment by sebasguts** [comment]
@wbhart I adressed all comments.

It is a very special case, and merely a wrapper for a Singular kernel function. I am not sure this is suitable for being in a general interface. But it could be used by one.

**Pull request merged**
