### PR TITLE
bump to 0.13.1

### PR DESCRIPTION
**Pull request by YueRen**

### CODE REVIEW

**Comment by YueRen** [comment]
@JuliaRegistrator register

**Comment by YueRen** [comment]
@JuliaRegistrator register

**Review by YueRen — COMMENTED** [review]
@JuliaRegistrator register

**Comment by thofma** [comment]
We must merge and then comment on the commit.

**Comment by YueRen** [comment]
Okay, nvm. Maybe I need to wait for this pull-request to be merged before pinging JuliaRegistrator in the comments (and perhaps I should have included this commit in my last pull-request).

**Comment by tthsqe12** [comment]
Yup, you have to comment on the actual commit
https://github.com/oscar-system/Singular.jl/pull/593/commits/b727700ed43e58421dad8308c6f1973211b72d6c

**Comment by tthsqe12** [comment]
Ok, try it here
https://github.com/oscar-system/Singular.jl/commit/232593e7978866ddd9bfc27c7df86c72fd2c92dc

If it doesn't work for you, I guess you need new permissions.

**Pull request merged**
