### PR TITLE
Added substitute_ith_variable

### PR DESCRIPTION
**Pull request by sebasguts**

### CODE REVIEW

**Comment by wbhart** [comment]
Could we get some spaces after commas.

By the way, I've just finished a massive project to improve the MPoly interface in AbstractAlgebra.jl. We intend to make the Singular.jl interface conform to this interface. That way some of the generic code there will also work for Singular.jl. (Not that there is much of it.)

This function occupies a strange place in this. We don't have such a function over there. But I am not at all sure what this would do anyway, e.g. if the polynomial you are evaluating at is not in the same ring. Does Singular create a new ring for this on the fly, or does it only allow polynomials in the same ring?

Of course we can have such a function just for Singular polynomials. But it might be useful to figure out if there's a way of unifying the two interfaces before we commit to that. I believe Daniel implemented a function to evaluate a multivariate at a list of polynomials in Flint.

**Comment by sebasguts** [comment]
> This function occupies a strange place in this. We don't have such a function over there. But I am not at all sure what this would do anyway, e.g. if the polynomial you are evaluating at is not in the same ring. Does Singular create a new ring for this on the fly, or does it only allow polynomials in the same ring?

The function only works for polys in the same ring.

> Of course we can have such a function just for Singular polynomials. But it might be useful to figure out if there's a way of unifying the two interfaces before we commit to that. I believe Daniel implemented a function to evaluate a multivariate at a list of polynomials in Flint.

This function is basically a thin wrapper around a Singular kernel function. If there is a standard interface, we can remove it later. This is also why I did not export it.

**Comment by fieker** [comment]
On the top end, user interface, there needs to be ONE function to
evaluate a multivariate polynomial at any array of points where this
makes sense: at the least points in any ring where the coefficients of
the poly can be embedded into.
There might be a large number of special evaluation functions, with
different names, signatures, ...
However, for the general one it should for all polynomials (univariate,
multivarite, sparse, ...) be the same.
I don't mind it being
 subst
 eval
 evaluate
 f(...)
 ...
but one for all!

Greetings
 Claus

**Comment by heiderich** [comment]
For reference: I think the request of @fieker is basically the following issue:
https://github.com/Nemocas/AbstractAlgebra.jl/issues/106
There I asked for the same feature. As far as I know, it does not exist yet. As a workaround one can combine `evaluate`, which can only evaluate at coefficients from the base ring, and `change_base_ring`.

**Comment by wbhart** [comment]
The problem with arbitrary evaluations is knowing what ring the result should be in. This is called complex coercion, which we don't provide in Nemo.

The best one could do is evaluate(R, f, [x, z, t], [a, b, c]) where a, b and c are plugged in for x, z and t and the result is evaluated in the ring R.

But that doesn't mean we don't want other kinds of evaluation, where it already makes sense without specifying the ring R. For example:

1) Evaluate at integers (already exists)
2) Evaluate at elements in the coefficient ring (already exists)
3) Evaluate at polynomials in the original multivariate ring (does not exist, but is trivial to implement, and I believe it has been implemented in Flint)

There's nothing stopping these from all being called "evaluate", though we probably want to overload the functional syntax for the case where all points are specified (or perhaps allow the original variable to be given when no evaluation is to be performed at that variable).

This Singular function would then just be a special case of the more general function 3 above.

**Comment by wbhart** [comment]
So talking to Hans about what Singular has, I think the following is the most general thing we can implement for evaluation of a multivariate f \in R[x, y, z]

1) Evaluate *any* number of variables at elements of R[x, y, z] (this includes at elements of R or integers)
2) Given a ring S and a map s : R -> S, evaluate *all* variables of f at elements of S (this includes the case where R lives in S, i.e. s is an injection)

I think the functional syntax f(a, b, c) should be reserved for case 2 with the restriction that elements of R automatically coerce into S and all of a, b, c have the same parent S, and of course also for case 1, e.g. f(a, y, b) where a, b in R[x, y, z].

**Comment by wbhart** [comment]
I would propose having a version of the evaluate function that takes a map, of course. If one is not provided, it should just assume there is a canonical embedding defined. If not the function will just tell you something is missing.

We also discussed what happens if you evaluate at elements of a noncommutative ring. I think we will want to allow that, where evaluation assumes that the variables are multiplied in the order they are specified when creating the polynomial ring, i.e. evaluating x^2*y at x, y = a, b will compute a^2*b not b*a^2. This seems like a reasonable tradeoff given that you might know that all the values you are using are in the centre of your algebra, even if the system doesn't. In cases where they actually aren't, some sensible interpretation is given.

Obviously much better algorithms exist for evaluating polynomials at points in a commutative ring than in a noncommutative ring. (Such as the one in Flint.)

**Pull request merged**
