### PR TITLE
Rename variables only on the Singular side

### PR DESCRIPTION
**Pull request by 8d1h**
Hi! I understand that variable renaming is necessary due to Singular's parsing, however I also really do want to use fancy unicode for variable names :)

Here is a (rough) proposal to do the renaming only on the Singular side, so in Julia variables will be printed the way they are defined. Also the caching uses the variable names *before* renaming, so we can have
```julia
julia> PolynomialRing(QQ, ["α"])[1] === PolynomialRing(QQ, ["x"])[1]
false
```

### CODE REVIEW

**Review by tthsqe12 — CHANGES_REQUESTED** [review]
Yes, I believe this to be a good idea. Just two points:
1. The `all_symbols` function in `src/MessyHacks.jl` should be renamed `all_singular_symbols` so that we don't get confused.
2. The `src/number/n_GF.jl` also has a rename that should be changed.

Other than that, looks good.

**Comment by 8d1h** [comment]
Thanks, I'll do these.

BTW, is there a libsingular function that can obtain the variable names for function field, like the `rRingVar` for polynomial rings?

**Comment by tthsqe12** [comment]
Yes, there is a zero-based interface with an example here
https://github.com/oscar-system/Singular.jl/blob/cedd61598b4fb146606508c114fe1d72c7305630/src/caller.jl#L170-L171

**Comment by hannes14** [comment]
libsingular has n_ParameterName (Singular.method("n_ParameterName", [](int i, coeffs r))

**Comment by 8d1h** [comment]
Thanks, I changed it for function fields and also the renaming for finite fields.

One last bit: when printing a polynomial ring, the string is directly read from Singular so we get renamed variables. Do we want to change this too?

**Comment by tthsqe12** [comment]
At some point we need to see what singular actually is working with. Singular's native string representation of the ring is a great way to have this information.

**Pull request merged**
