### PR TITLE
N_GField: add a `gen` method

### PR DESCRIPTION
**Pull request by rfourquet**

### CODE REVIEW

**Comment by wbhart** [comment]
I think generator in this context in Nemo means generator of the multiplicative group, i.e. the root of the Conway polynomial, x. It seems a shame to return 1 instead in Singular.

**Comment by thofma** [comment]
In Nemo in general it is just a generator as an algebra over the prime field. There is no guarantee that `gen` returns a generator for the multiplicative group in Nemo.

**Comment by rfourquet** [comment]
For `FqFinitField` for example, the docstring says:
>  Return the generator of the finite field. Note that this is only guaranteed to be a multiplicative generator if the finite field is generated by
>  a Conway polynomial automatically.

> It seems a shame to return 1 instead in Singular.

Actually, it looks like that `gen` here returns a multiplicative generator, at least in some cases:
```julia
julia> F, a = FiniteField(2, 3, "a")
(Finite Field of Characteristic 2 and degree 3, a)

julia> gen(F) == a
true

julia> [a^i for i = 1:8]
8-element Vector{n_GF}:
 a
 a^2
 a^3
 a^4
 a^5
 a^6
 1
 a
```

**Comment by thofma** [comment]
If it gives one for F_p where p is prime, then this is fine.

**Comment by rfourquet** [comment]
There is one [failing CI job](https://travis-ci.com/github/oscar-system/Singular.jl/jobs/398746405), with a segmentation fault, which surely is not caused by this patch... Are Singular.jl tests known to sometimes fail like this?

**Comment by wbhart** [comment]
I don't think there should be segfaults. But it's not guaranteed to be a problem with this patch.

Singular has a different type for F_p, but this is n_GF right? That's for fields of any degree. It's surely going to make sense long term for it to agree with Nemo, no?

**Comment by rfourquet** [comment]
> If it gives one for F_p where p is prime, then this is fine.

Ok, here this gives -1
```julia
julia> F, a = FiniteField(3, 1, "a")
(Finite Field of Characteristic 3 and degree 1, -1)

julia> a
-1
```
Shall I change that to `1` instead? Or do we have in Nemo already a function to compute a proper generator (primitive root)? like in Nemo:
```julia
julia> F, a = Nemo.FiniteField(3, 1, "a")
(Finite field of degree 1 over F_3, 2)
```

**Comment by thofma** [comment]
`-1` is the same as `2`.

**Comment by rfourquet** [comment]
> -1 is the same as 2.

Oh right :facepalm: , `gen` already does give a generator then :)

**Comment by rfourquet** [comment]
> Singular has a different type for F_p, but this is n_GF right? That's for fields of any degree.
RIght. For `Fp` (Z/pZ), I didn't add `gen`, it's not implemented for `Nemo.GF`.

> It's surely going to make sense long term for it to agree with Nemo, no?

I can't say :)

**Comment by thofma** [comment]
I remember @fingolfin mentioning random segfaults. Not sure if this is related to what he saw.

**Comment by rfourquet** [comment]
Good to go?

**Comment by wbhart** [comment]
Yes, I misunderstood what this patch was doing

**Comment by rfourquet** [comment]
Bump :)

**Comment by rfourquet** [comment]
Thanks!

**Pull request merged**
