### PR TITLE
Project.toml: remove unnecessary dependencies

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by wbhart** [comment]
This seems to cause failures related to the PR.

**Comment by fingolfin** [comment]
Those failures are on Julia nightly only, and they are not caused by this PR; they affect several (all?) of our packages. As a matter of fact, this PR was an attempt to see if this might cure it.

As it is, some recent merge in Julia master causes this; I have a strong suspicion that it was the Fake JLL PR that causes this -- because the first error is about GMP_jll, which is now one of the fake JLLs:
```
ERROR: LoadError: ArgumentError: Package GMP_jll [781609d7-10c4-51f6-84f2-b8444358ff6d] is required but does not seem to be installed:
 - Run `Pkg.instantiate()` to install all recorded dependencies.
```

**Comment by fingolfin** [comment]
OK, this is already reported: https://github.com/JuliaLang/julia/issues/38654

**Comment by wbhart** [comment]
I see. Otherwise I suppose we merge this? If the dependencies are unnecessary, seems ok.

**Pull request merged**
