### PR TITLE
Add fancy orderings

### PR DESCRIPTION
**Pull request by tthsqe12**
goes with https://github.com/oscar-system/libsingular-julia/pull/26
This cannot be tried by anyone else atm because it requires a new libsingular-julia, but I would just put this out there for comments: this is approximately what it will look like. @wdecker @hannes14 
Note that this is a singular.jl-only change. Orderings will be much different in oscar.

Both the old `ordering=symbol` and the new `ordering=fancystuff` will be supported.

```julia
julia> PolynomialRing(QQ, map(i->"x"*string(i), 1:8), ordering = :negdegrevlex)[1]
Singular Polynomial Ring (QQ),(x1,x2,x3,x4,x5,x6,x7,x8),(ds(8),C)

julia> PolynomialRing(QQ, map(i->"x"*string(i), 1:8), ordering = ds_order())[1]
Singular Polynomial Ring (QQ),(x1,x2,x3,x4,x5,x6,x7,x8),(ds(8),C)
```

This seems to match original singular in behaviour

```julia
julia> a = M_order([1 2; 3 5])*lp_order(3)*wp_order([1, 2, 3])
M_order([1 2; 3 5]) * lp_order(3) * wp_order([1, 2, 3])

julia> PolynomialRing(QQ, "x".*string.(1:8), ordering = a)[1]
Singular Polynomial Ring (QQ),(x1,x2,x3,x4,x5,x6,x7,x8),(M(1,2,3,5),lp(3),wp(1,2,3),C)

julia> PolynomialRing(QQ, "x".*string.(1:9), ordering = a)[1]
ERROR: mismatch of number of vars (9) and ordering (8 vars)
Stacktrace:
 [1] error(::String, ::Int64, ::String, ::Int64, ::String)
   @ Base ./error.jl:42
 [2] serialize_ordering(nvars::Int64, ord::Singular.sordering)
   @ Singular ~/.julia/dev/Singular/src/poly/poly.jl:1292
 [3] PolyRing{n_Q}(R::Rationals, s::Vector{Symbol}, ord::Singular.sordering, cached::Bool, degree_bound::Int64)
   @ Singular ~/.julia/dev/Singular/src/poly/PolyTypes.jl:100
 [4] #PolynomialRing#45
   @ ~/.julia/dev/Singular/src/poly/poly.jl:1323 [inlined]
 [5] top-level scope
   @ REPL[4]:1
```

This also seems to match original singular in regards to variable counts.

```julia
julia> a = dp_order(3)*lp_order(3)
dp_order(3) * lp_order(3)

julia> PolynomialRing(QQ, "x".*string.(1:6), ordering = a)[1]
Singular Polynomial Ring (QQ),(x1,x2,x3,x4,x5,x6),(dp(3),lp(3),C)

julia> PolynomialRing(QQ, "x".*string.(1:7), ordering = a)[1]
Singular Polynomial Ring (QQ),(x1,x2,x3,x4,x5,x6,x7),(dp(3),lp(4),C)

julia> PolynomialRing(QQ, "x".*string.(1:5), ordering = a)[1]
ERROR: mismatch of number of vars (5) and ordering
Stacktrace:
 [1] error(::String, ::Int64, ::String)
   @ Base ./error.jl:42
 [2] serialize_ordering(nvars::Int64, ord::Singular.sordering)
   @ Singular ~/.julia/dev/Singular/src/poly/poly.jl:1274
 [3] PolyRing{n_Q}(R::Rationals, s::Vector{Symbol}, ord::Singular.sordering, cached::Bool, degree_bound::Int64)
   @ Singular ~/.julia/dev/Singular/src/poly/PolyTypes.jl:100
 [4] #PolynomialRing#45
   @ ~/.julia/dev/Singular/src/poly/poly.jl:1323 [inlined]
 [5] top-level scope
   @ REPL[8]:1
```

Finally, I will probably opt to catch bad input as soon as possible.

```julia
julia> M_order([1 2; 3 6])
ERROR: weight matrix must nonsingular
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] M_order(m::Matrix{Int64}, checked::Bool)
   @ Singular ~/.julia/dev/Singular/src/poly/poly.jl:1229
 [3] M_order(m::Matrix{Int64})
   @ Singular ~/.julia/dev/Singular/src/poly/poly.jl:1227
 [4] top-level scope
   @ REPL[2]:1

```

### CODE REVIEW

**Comment by thofma** [comment]
Nice. Just two (random) thoughts.
- How about `ordering` instead of `order`?
- If it is `order(ing)_bla` instead of `bla_order(ing)` the different orderings will be easier to discover.

**Comment by wdecker** [comment]
Thanks Dan!
1) I support Tommy with his thoughts.
2) Hans will send some remarks with regard to module orderings. Additionally, I wonder whether we should have Schreyer orderings.

**Comment by hannes14** [comment]
Even if not handling modules here: maybe we should add module orderings
position_over_term (..,C), term_over_position(C,...).

**Comment by tthsqe12** [comment]
I can add the C, c, S, and s orderings.

**Review by fieker — COMMENTED** [review]
Is there any particular reason to not use the oscar-module for those orderings? Or their syntax/ implementation?
simplify is missing: a product of orderings can easily have more rows than variables...
also missing: comparison of orders

**Comment by tthsqe12** [comment]
> Is there any particular reason to not use the oscar-module for those orderings? Or their syntax/ implementation?

I was trying to keep it close to the original singular. If instead of `ordering_dp(3)*ordering_dp(4)`, which I have done here, you are talking about `ordering(1:3, :degrevlex)*ordering(4:7, :degrevlex)`, that is probably possible, but the wp, Wp, ws, Ws, and a orderings need to be considered.

> simplify is missing: a product of orderings can easily have more rows than variables...

I am not sure what simplify is supposed to do.

> also missing: comparison of orders

comparison for equality?

**Comment by fieker** [comment]
On Thu, Apr 29, 2021 at 09:11:40AM -0700, tthsqe12 wrote:
> 
> > Is there any particular reason to not use the oscar-module for those orderings? Or their syntax/ implementation?
> 
> I was trying to keep it close to the original singular. If instead of `ordering_dp(3)*ordering_dp(4)`, which I have done here, you are talking about `ordering(1:3, :degrevlex)*ordering(4:7, :degrevlex)`, that is probably possible, but the wp, Wp, ws, Ws, and a orderings need to be considered.
> 
> > simplify is missing: a product of orderings can easily have more rows than variables...
> 
> I am not sure what simplify is supposed to do.
given an m x n matrix as a result of order * order * order * order ....
for suitable orders with overlapping variables (all legal - Hans told me
about them), find a unique n x n matrix describing the same ordering
> 
> > also missing: comparison of orders
> 
> comparison for equality?
and hash and such. For Groebnerwalk, potentially, we have to deal with
lots of orders

**Comment by fieker** [comment]
On Thu, Apr 29, 2021 at 09:11:40AM -0700, tthsqe12 wrote:
> 
> > Is there any particular reason to not use the oscar-module for those orderings? Or their syntax/ implementation?
> 
> I was trying to keep it close to the original singular. If instead of `ordering_dp(3)*ordering_dp(4)`, which I have done here, you are talking about `ordering(1:3, :degrevlex)*ordering(4:7, :degrevlex)`, that is probably possible, but the wp, Wp, ws, Ws, and a orderings need to be considered.
The reasons the wp, Wp, ... are not in are
 - I got tired
 - I don't know what they are doing
 - I decided after the frame and API is defined, s.o. more geometric,
   possibly Hans, can follow up and fill in...

**Comment by tthsqe12** [comment]
I am fairly happy with this. Here is a summary of the orderings and some of the discussions here:
1. You will now type in something like `PolynomialRing(QQ, ["x","y","z","t"], ordering=ordering_lp(2)*ordering_dp(2))` as the equivalent of singular's `ring r = 0, (x,y,z,t), (lp(2), dp(2))`. The test code https://github.com/oscar-system/Singular.jl/pull/418/files#diff-9296b95ab4b7a1be6e8482b50892c9e973e081608978ec8209c47fd628e8af60R61 provides a good look at how it works.
2. The ordering of a polyring is still available as `ordering(::PolyRing)` but it is no longer a `Symbol` but rather an `sordering` . You can iterate through these objects and call `ordering_{as_symbol|size|weights}` to get info on the ordering.
3. As far as I could tell from reading the documentation, singular does not provide a `simplify` function on orderings, so if this function is going to exist, it will have to be provided by oscar.
4. Similarly, equality testing of orderings will probably have to be done in oscar.
5. I am happy to have the orderings in singular.jl be as simply as possible a wrapper of the orderings that singular provides. The orderings in oscar will have to be converted when possible to the singular orderings at the time of the creation of the polynomial ring with said fancy ordering.

**Comment by thofma** [comment]
I think this is a reasonable approach.

**Pull request merged**
