### PR TITLE
Try to fix .travis.yml

### PR DESCRIPTION
**Pull request by thofma**

### CODE REVIEW

**Comment by sebasguts** [comment]
One of the tests seems to be broken. Should I fix it or do you want to do it?

**Comment by wbhart** [comment]
Yes, it's been broken for a while but we didn't actually know what was going on. I believe we were going to ask you to take a look at it anyway.

**Comment by wbhart** [comment]
Oh sorry, I thought you were @sebasguts We can let him look at it. It's a technical problem with CxxWrap, I believe. Not something easily fixed.

**Comment by sebasguts** [comment]
The bug that appeared should be easily fixed. I hope this thing will do the trick . . .

**Comment by sebasguts** [comment]
Looks good now :). Thanks a lot. Do you want to remove the Bla commit, or do you want us to keep it for historical reasons?

**Comment by thofma** [comment]
I have cleaned up the `.travis.yml` and rebased.

**Pull request merged**
