### PR TITLE
Reenable Nemo coeff rings for singular

### PR DESCRIPTION
**Pull request by sebasguts**
@wbhart 
This is a first try to get Nemo coefficient rings working again in Singular.jl

I would guess the first step for testing this is trying to get the command
```
Singular.PolynomialRing(Nemo.ZZ,["x"])
```
working, is that right?

### CODE REVIEW

**Comment by wbhart** [comment]
Great! Yes, that would be a first step. Of course we have tests commented out for this.

**Comment by wbhart** [comment]
Looks good. Is the PR ready to go? Or should I wait for some test code to be switched on?

I can work on the other similar files, or I could get Sachin to work on it, depending on what you think.

**Comment by sebasguts** [comment]
Not at all ready to go. It is just an initial setup. I will get it ready to go tomorrow and message you.

**Comment by sebasguts** [comment]
@wbhart please have a look

**Comment by wbhart** [comment]
Looks pretty neat. There are the following:

* In NumberTypes.jl there is still a println
* When creating the big struct, you can specify a bunch of zeroes in a row using [0 for i in 1:5]... and similarly for the Ptr{Void}'s. The ... syntax interpolates the array as a tuple. (Also is it necessary to defined the constructor for this type as an external constructor instead of an internal one?)
* We should verify that the cache is still working correctly, e.g. by doing some computation that uses a lot of external coeffs and checking that the part that frees stuff from the cache ever gets triggered. The main thing that could go wrong is if actual addresses of the objects in question are not passed. So it presumably works, but always good to check, otherwise we will have a leak.

**Comment by sebasguts** [comment]
I applied comments 1&2, but had to leave the outer constructor, as the `...` syntax does not work inside `new`.

Do you have any test computation we could use? Or just run the tests a lot of times? I am pretty sure the caches work, though, as I had several problems including them.

**Comment by wbhart** [comment]
I think I will now work on this and try to get it working again. We have someone at the Gap-Singular days that could really use this functionality.

**Comment by wbhart** [comment]
Superceded.

**Pull request closed without merging**
