### PR TITLE
Project

### PR DESCRIPTION
**Pull request by wbhart**

### CODE REVIEW

**Comment by thofma** [comment]
I think the build is timing out on the earlier julia versions. I think `.travis.yml` needs some heartbeat. You could try something like the following::
```yml
script:
  - julia -e 'using Pkg; Pkg.add(PackageSpec(path=pwd()))'
  - while sleep 30; do echo "still alive"; done &
  - julia -e 'using Pkg; Pkg.build("Singular");'
  - julia -e 'using Pkg; Pkg.test("Singular");'
```

**Comment by wbhart** [comment]
Yeah, but then the documentation stage doesn't seem to exist.

**Comment by wbhart** [comment]
No actually I think it was just not running due to failures on OSX. I've asked repeatedly for someone with a Mac to try and fix the build (the linker doesn't find GMP), but no one seems to either notice or care. So now I'm allowing failures on OSX. We'll see how long that lasts before someone notices.

**Comment by thofma** [comment]
Sorry, the commands I wrote are not working.

**Comment by wbhart** [comment]
Yeah the Pkg.add is doing the build presumably. I'll try again.

**Pull request merged**
