### PR TITLE
Add promotion rules for fmpz -> Singular types

### PR DESCRIPTION
**Pull request by fingolfin**
Mostly for conveniences in code which works directly with Singular.jl objects.

Honestly, I am not sure if this is a good idea or a really bad one... Wonder if @wbhart or @fieker have any thoughts about this (I'll have no hard feelings if this is not merged; but it was useful for me to learn more about the AA/Nemo promotion system ;-) ).

### CODE REVIEW

**Comment by wbhart** [comment]
I don't have any objections, if the test cases do actually trigger those promote_rules.

**Comment by fingolfin** [comment]
Actually, not all are covered yet (Codecov report reveals this). I'll fix that.

**Comment by fingolfin** [comment]
OK, I extended the tests and made them more systematic. Let's see if that covered all the new rules (once the Codecov report is in)

**Comment by fingolfin** [comment]
On https://codecov.io/gh/oscar-system/Singular.jl/pull/364 one can verify that all the new promotion rules are triggered (plus some more code which wasn't covered before)

**Review by wbhart — APPROVED** [review]

**Pull request merged**
