### PR TITLE
Bugfix

### PR DESCRIPTION
**Pull request by raulepure**
Fixed a bug related to multiplying fmpq with spoly over n_unknown.

### CODE REVIEW

**Comment by fingolfin** [comment]
Thank you! But what was the bug? As in: can you provide a brief code snippet demonstrating it? Even better, could you perhaps add a brief test which demonstrates that the bugfix is effective?

**Comment by raulepure** [comment]
Sorry for the short explanation. Here a more detailed one:
I encountered an error regarding multiplication of fmpq elements with Singular spolys in OSCAR. Here is a minimal example:
``` 
julia> a = QQ(5)
5

julia> K = Singular.CoefficientRing(QQ)
Singular coefficient ring over Rational Field

julia> R, (x, y, z) = Singular.PolynomialRing(K, ["x", "y", "z"])
(Singular Polynomial Ring (Coeffs(19)),(x,y,z),(dp(3),C), Singular.spoly{Singular.n_unknown{fmpq}}[x, y, z])

julia> a*x
ERROR: MethodError: Singular Polynomial Ring (Coeffs(19)),(x,y,z),(dp(3),C)(::Singular.n_unknown{fmpq}) is ambiguous. Candidates:
  (R::Singular.PolyRing{T})(n::T) where T<:RingElem in Singular at /home/epure/.julia/dev/Singular/src/poly/poly.jl:1096
  (b::AbstractAlgebra.Ring)(a::Singular.n_unknown) in Oscar at /home/epure/.julia/dev/Oscar/src/Rings/mpoly.jl:281
  (R::Singular.PolyRing{S})(n::T) where {S<:RingElem, T<:RingElem} in Singular at /home/epure/.julia/dev/Singular/src/poly/poly.jl:1103
Possible fix, define
  (::Singular.PolyRing{T})(::T) where T<:Singular.n_unknown
Stacktrace:
 [1] (::Singular.PolyRing{Singular.n_unknown{fmpq}})(::fmpq) at /home/epure/.julia/dev/Singular/src/poly/poly.jl:1103
 [2] *(::fmpq, ::Singular.spoly{Singular.n_unknown{fmpq}}) at /home/epure/.julia/packages/AbstractAlgebra/NyIUy/src/Rings.jl:76
 [3] top-level scope at REPL[5]:1
```
Running the code did not cause an error in Singular.jl. 
I created the pull request on the Singular.jl side, since it involves conversion of elements in Singular.jl. 

If it is not appropriate to change it in Singular.jl, I can create a pull request on the OSCAR side (with a small test).

**Comment by hannes14** [comment]
Singular.jl is the right place, just add your example to the tests

**Comment by fingolfin** [comment]
@raulepure as Hans said, it is perfectly appropriate here. Thank you very much for the fix! The example you pasted above could basically be turned directlt into a test

**Comment by raulepure** [comment]
@fingolfin , @hannes14 
I checked the Singular.jl tests and this is tested in "nemo-test.jl". (Replacing Hecke with Nemo in my code snippet, but this does not change anything with the Oscar error and with its fix)
As I mentioned , Singular.jl has no problem with this. 
In my oppinion it would make more sense to add the test to Oscar.jl, since the error occurs there, and, as you two pointed out, the code for the fix here in Singular.jl. Or is there a problem with this approach?

**Comment by fingolfin** [comment]
@raulpure I don't understand: what do you mean when you say "Running the code did not cause an error in Singular.jl."? it certainly does for me:
```
$ julia
u               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.4.2 (2020-05-23)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using Singular

Welcome to Nemo version 0.17.0

Nemo comes with absolutely no warranty whatsoever

Singular.jl, based on
                     SINGULAR                                 /
 A Computer Algebra System for Polynomial Computations       /  Singular.jl: 0.3.1
                                                           0<   Singular   : 4.2.1-4
 by: W. Decker, G.-M. Greuel, G. Pfister, H. Schoenemann     \
FB Mathematik der Universitaet, D-67653 Kaiserslautern        \


julia> a = QQ(5)
5

julia> K = Singular.CoefficientRing(QQ)
Singular coefficient ring over Rational Field

julia> R, (x, y, z) = Singular.PolynomialRing(K, ["x", "y", "z"])
(Singular Polynomial Ring (Coeffs(19)),(x,y,z),(dp(3),C), spoly{Singular.n_unknown{n_Q}}[x, y, z])

julia> a*x
ERROR: StackOverflowError:
Stacktrace:
 [1] nApplyMapFunc(::Ptr{Nothing}, ::CxxWrap.CxxWrapCore.CxxPtr{Singular.libSingular.number}, ::CxxWrap.CxxWrapCore.CxxPtr{Singular.libSingular.coeffs}, ::CxxWrap.CxxWrapCore.CxxPtr{Singular.libSingular.coeffs}) at /Users/mhorn/.julia/packages/CxxWrap/94t40/src/CxxWrap.jl:590
 [2] numerator(::n_Q) at /Users/mhorn/.julia/packages/Singular/GGfzi/src/number/n_Q.jl:59
 [3] Rational{BigInt}(::n_Q) at /Users/mhorn/.julia/packages/Singular/GGfzi/src/number/n_Q.jl:361
 [4] (::CoefficientRing{n_Q})(::n_Q) at /Users/mhorn/.julia/packages/Singular/GGfzi/src/number/n_unknown.jl:218 (repeats 25982 times)
 [5] (::PolyRing{Singular.n_unknown{n_Q}})(::n_Q) at /Users/mhorn/.julia/packages/Singular/GGfzi/src/poly/poly.jl:1099
 [6] *(::n_Q, ::spoly{Singular.n_unknown{n_Q}}) at /Users/mhorn/.julia/packages/AbstractAlgebra/NyIUy/src/Rings.jl:76
 [7] top-level scope at REPL[5]:1
```

So I can easily reproduce this with just Singular.jl loaded. Since the fix is here, I would also like the test for the fix to be here (for various reasons, e.g. so that one can identify that the belong together via the commit history).

**Comment by fingolfin** [comment]
In particular, I don't see how Oscar.jl is involved at all?

**Comment by raulepure** [comment]
@fingolfin Sorry for all the confusion. I think we are talking about two different bugs. 
My example was done using Oscar and trying to use  Singular.jl in Oscar. I just forgot to write the "using Oscar" part in the code snippet. The bug I observed only appears, when trying to multiply Oscars rational numbers with Singular n_unknown inside Oscar code.
Here is the full example:

```
julia> using Oscar
┌ Warning: More than one copy of gmp already loaded, using the 1st one
└ @ LoadFlint ~/.julia/packages/LoadFlint/42zpR/src/LoadFlint.jl:40
 -----    -----    -----      -      -----
|     |  |     |  |     |    | |    |     |
|     |  |        |         |   |   |     |
|     |   -----   |        |     |  |-----
|     |        |  |        |-----|  |   |
|     |  |     |  |     |  |     |  |    |
 -----    -----    -----   -     -  -     -

...combining (and extending) ANTIC, GAP, Polymake and Singular
Version 0.4.0-dev ...
 ... which comes with absolutely no warranty whatsoever
Type: '?Oscar' for more information
(c) 2019-2020 by The Oscar Development Team

julia> K = Singular.CoefficientRing(QQ)
Singular coefficient ring over Rational Field

julia> a = QQ(5)
5

julia> typeof(a)
fmpq

julia> R, (x, y, z) = Singular.PolynomialRing(K, ["x", "y", "z"])
(Singular Polynomial Ring (Coeffs(19)),(x,y,z),(dp(3),C), Singular.spoly{Singular.n_unknown{fmpq}}[x, y, z])

julia> a*x
ERROR: MethodError: Singular Polynomial Ring (Coeffs(19)),(x,y,z),(dp(3),C)(::Singular.n_unknown{fmpq}) is ambiguous. Candidates:
  (R::Singular.PolyRing{T})(n::T) where T<:RingElem in Singular at /home/epure/.julia/dev/Singular/src/poly/poly.jl:1096
  (b::AbstractAlgebra.Ring)(a::Singular.n_unknown) in Oscar at /home/epure/.julia/dev/Oscar/src/Rings/mpoly.jl:281
  (R::Singular.PolyRing{S})(n::T) where {S<:RingElem, T<:RingElem} in Singular at /home/epure/.julia/dev/Singular/src/poly/poly.jl:1103
Possible fix, define
  (::Singular.PolyRing{T})(::T) where T<:Singular.n_unknown
Stacktrace:
 [1] (::Singular.PolyRing{Singular.n_unknown{fmpq}})(::fmpq) at /home/epure/.julia/dev/Singular/src/poly/poly.jl:1103
 [2] *(::fmpq, ::Singular.spoly{Singular.n_unknown{fmpq}}) at /home/epure/.julia/packages/AbstractAlgebra/NyIUy/src/Rings.jl:76
 [3] top-level scope at REPL[5]:1
```
Oscars rational numbers are fmpq's, which I can obtain in Singular.jl through Nemo. The following code shows, that this does NOT create an error in Singular.jl:

```
julia> using Singular
┌ Warning: More than one copy of gmp already loaded, using the 1st one
└ @ LoadFlint ~/.julia/packages/LoadFlint/42zpR/src/LoadFlint.jl:40
Singular.jl, based on
                     SINGULAR                                 /
 A Computer Algebra System for Polynomial Computations       /  Singular.jl: 0.3.1-dev
                                                           0<   Singular   : 4.2.1-4
 by: W. Decker, G.-M. Greuel, G. Pfister, H. Schoenemann     \
FB Mathematik der Universitaet, D-67653 Kaiserslautern        \


julia> import Nemo

julia> K = Singular.CoefficientRing(Nemo.QQ)
Singular coefficient ring over Rational Field

julia> a = Nemo.QQ(5)
5

julia> typeof(a)
Nemo.fmpq

julia> R, (x, y, z) = Singular.PolynomialRing(K, ["x", "y", "z"])
(Singular Polynomial Ring (Coeffs(19)),(x,y,z),(dp(3),C), spoly{Singular.n_unknown{Nemo.fmpq}}[x, y, z])

julia> a*x
5*x
```
That is the reason why I asked to write test-code in Oscar, since the error occurs there. 

My fix does NOT resolve your problem with the Singular.jl rationals and their conversion to a Singular Coefficient Ring. 
This is a different fix. 
I'm not sure how to do this for the moment, I can have a look at it.

**Comment by fingolfin** [comment]
Well, let's merge this then; a test anywhere would still be nice, though :-)

**Pull request merged**
