### PR TITLE
code to create the module generated by polynomials

### PR DESCRIPTION
**Pull request by fieker**
the problem is
S = Singular.PolynomialRing(Singular.QQ, ["x", "y"])
I = Singular.Ideal(S[1], S[2])
M = Singular.Module(S[1], I.ptr)
I = 1
M = 1
Base.GC.gc()

this deletes the ideal twice: the finalizer on the I will delete the
underlying Singular object and the finalizer on M will do the same (as
modules and ideals are "the same" in Singular)

This provides
M = Singular.Module(S[1], S[2]...)

### CODE REVIEW

**Comment by fieker** [comment]
Possibly
Singular.Module(S[1], I.ptr)
should be removed?

**Comment by wbhart** [comment]
Some context would be helpful. Is this user code?

If so, the line Singular.Module(S[1], I.ptr) is not valid. It should not be called like that by a user.

If not, where is this line of code from?

The comments also don't make sense. The second comment starts with "otherwise", but it's not clear where the first part of the sentence is.

Anyhow, we use reference counting, so it's fine for two objects to refer to the same ring. It's just that when they are created, they both need to update the reference count.

**Comment by fieker** [comment]
On Mon, Dec 07, 2020 at 02:18:11AM -0800, wbhart wrote:
> Some context would be helpful. Is this user code?
Yes/no/maybe:

We now have a (first version of) std_lift, however, the current input is
a smodule. So: given an ideal (where I want the lift_std function for),
how do I get a smodule?

OK: for this particular application: obviously by providing a second
signature for lift_std, however, it is frequently useful to not use
ideals but modules...
In Singular proper they are the same anyway.
> 
> If so, the line Singular.Module(S[1], I.ptr) is not valid. It should not be called like that by a user.
This is in Singular.jl/src/module/module.jl
line 192 (and has been there for some time(?))
I agree: it should not be called by a user - nor by a programmer, but I
assume there was a reason for providing this...
> 
> If not, where is this line of code from?
> 
> The comments also don't make sense. The second comment starts with "otherwise", but it's not clear where the first part of the sentence is.
> 
> Anyhow, we use reference counting, so it's fine for two objects to refer to the same ring. It's just that when they are created, they both need to update the reference count.
I wasn't aware of sideal/ smodule doing ref counting, if they do, this
can be simplified....

**Comment by wbhart** [comment]
No, you are right. I thought this was an issue with the ring being deleted twice. We have reference counting on the ring.

In this case, the ideal should have been copied when the module was created. Otherwise it will be cleaned up twice. So this is just a clear bug. You certainly don't want the same object in there, otherwise if the ideal is modified, the module will be too!

**Comment by fieker** [comment]
On Mon, Dec 07, 2020 at 02:53:44AM -0800, wbhart wrote:
> No, you are right. I thought this was an issue with the ring being deleted twice. We have reference counting on the ring.
> 
> In this case, the ideal should have been copied when the module was created. Otherwise it will be cleaned up twice. So this is just a clear bug. You certainly don't want the same object in there, otherwise if the ideal is modified, the module will be too!
> 
I don't know what one wants there. As you said before: creating a Module
from an ideal ptr is nothing for normal people. If this signature makes
sense at all: I don't know. That is for @hannes14 to say...

**Comment by wbhart** [comment]
Not for normal people, no, it doesn't. But I assume this is used internally for some critical purpose, otherwise it wouldn't have been added. We have numerous similar functions elsewhere in the package. For example, one can create a matrix from a module, from memory. I hope that is not similarly broken.

**Comment by hannes14** [comment]
Am Mon, Dec 07, 2020 at 02:58:44AM -0800 schrieb Claus Fieker:
> On Mon, Dec 07, 2020 at 02:53:44AM -0800, wbhart wrote:
> > No, you are right. I thought this was an issue with the ring being deleted twice. We have reference counting on the ring.
> > 
> > In this case, the ideal should have been copied when the module was created. Otherwise it will be cleaned up twice. So this is just a clear bug. You certainly don't want the same object in there, otherwise if the ideal is modified, the module will be too!
> > 
> I don't know what one wants there. As you said before: creating a Module
> from an ideal ptr is nothing for normal people. If this signature makes
> sense at all: I don't know. That is for @hannes14 to say...
It is only useful for newly (i.e. by the Singular kernel) created
results, to wrap them in julia objects.

**Comment by wbhart** [comment]
Yes, that sounds correct @hannes14

**Comment by hannes14** [comment]
Am Mon, Dec 07, 2020 at 02:53:44AM -0800 schrieb wbhart:
> No, you are right. I thought this was an issue with the ring being deleted twice. We have reference counting on the ring.
> 
> In this case, the ideal should have been copied when the module was created. Otherwise it will be cleaned up twice. So this is just a clear bug. You certainly don't want the same object in there, otherwise if the ideal is modified, the module will be too!
> 
sideal and smodule are not the same even if the have the same type in C:
if I is generated by x, I as smodule would be generated by x*gen(1).
THe Singular kernel function for transfering an ideal (or a matrix) to an
module is id_Matrix2Module - it is also in libsingular-julia,
but seems not to be used in Singular.jl

**Comment by wbhart** [comment]
Ah, that's an even more serious issue. Yes, that will need fixing.

**Comment by wbhart** [comment]
I opened a ticket for this and another to document the issues with the functions taking ptr's.

**Comment by wbhart** [comment]
Can this PR be closed?

**Comment by fieker** [comment]
Functionality is superseded, comments are useful though

**Pull request closed without merging**
