### PR TITLE
zero poly lacks a leading exponent

### PR DESCRIPTION
**Pull request by tthsqe12**

### CODE REVIEW

**Comment by wdecker** [comment]
I suggest, to do the same for the leading_monomial of the zero polynomial.

**Comment by tthsqe12** [comment]
The current leading_monomial in AA returns zero for zero input, so for consistency we would have to think about changing it there too.

**Comment by wdecker** [comment]
Yes, I agree. However, it is unclear to me whether this would cause trouble somewhere in the system. In any case, zero is NOT a monomial from a mathematical point of view.

**Comment by tthsqe12** [comment]
I am giving it a try.
https://github.com/Nemocas/AbstractAlgebra.jl/pull/1109

**Comment by tthsqe12** [comment]
Doesn't seem to cause any trouble.

**Pull request merged**
