### PR TITLE
Added minor functions for local rings

### PR DESCRIPTION
**Pull request by raulepure**
Added check, whether the ring has a local/mixed ordering.
Added function to compute the order of a polynomial. 
Added function to compute a minimal generating set of an ideal/ a module in case the ring is local.

Tests only added for the minimal generating set functions.

### CODE REVIEW

**Comment by wbhart** [comment]
I am probably missing something, but I only see tests for one function. I think that especially as it has to interact with Singular, they should all have simple tests, even if only to verify the interfacing is working.

Also, simply adding docstrings is not quite enough. One should also import those docstrings into relevant sections in the actual documentation in the doc directory.

**Comment by wbhart** [comment]
@raulepure Just in case you didn't get the message I left on the PR.

**Comment by raulepure** [comment]
I will add tests for the other functions too. 
I will update the documentation file, too. In this request I will also include the documentation of my older pull requests, if this is not a problem.

**Comment by wbhart** [comment]
That will be no problem.

**Comment by wbhart** [comment]
Just let me know when you are ready.

**Comment by raulepure** [comment]
I'm finished, if you do not have any more remarks.

**Pull request merged**
