### PR TITLE
CI.yml: also build documentation and run doctests

### PR DESCRIPTION
**Pull request by rfourquet**

### CODE REVIEW

**Comment by rfourquet** [comment]
So this needs tweaking... I try now:
- have docs run after tests, so that the build step doesn't have to be redone
- specify the exact version in docs, to be sure it matches one of the test runners 
- remove a bunch of versions temporarily just to not give useless work to test runners

**Comment by rfourquet** [comment]
I guess that before merging, a `DOCUMENTER_KEY` has to be created, for deploying the docs (cf. https://juliadocs.github.io/Documenter.jl/dev/man/hosting/#Authentication:-SSH-Deploy-Keys).

**Comment by thofma** [comment]
I have added a key pair for `DOCUMENTER_KEY`.

**Comment by thofma** [comment]
@rfourquet Should we just merge and see what happens?

**Comment by rfourquet** [comment]
> Should we just merge and see what happens?

I guess, but let's try to rerun CI to see if the "documentation" runner sees the `DOCUMENTER_KEY` (previous build, at https://github.com/oscar-system/Singular.jl/pull/301/checks?check_run_id=1379821354, showed

> `✘ ENV["DOCUMENTER_KEY"] exists`

under "deployment criteria").

**Comment by rfourquet** [comment]
The CI build still doesn't know about `DOCUMENTER_KEY`, but I suspect it's because it's a PR made from a fork. I guess that the depolyment would occur when the PR is merged. So yeah, I would say let's merge and see if this works when we make a documentation change.

**Pull request merged**
