### PR TITLE
Added "change_base_ring" to Singular.jl

### PR DESCRIPTION
**Pull request by raulepure**
Added change_base_ring functionality to Singular with tests and documentation.
This pull request addresses Issue #157.

### CODE REVIEW

**Comment by wbhart** [comment]
@raulepure if you update the version number in Project.toml for AbstractAlgebra to 0.7.1 I think this will now pass.

**Comment by wbhart** [comment]
I assume the test failure there is not related to this PR?

I will open a ticket for it.

**Comment by raulepure** [comment]
No the failed test is not related to change base ring

**Comment by wbhart** [comment]
Yay!

Thanks for your patience @raulepure

**Pull request merged**
