### PR TITLE
Treat n_unknown{Nemo.FieldElem} as field elements

### PR DESCRIPTION
**Pull request by 8d1h**

### CODE REVIEW

**Comment by tthsqe12** [comment]
How about at least one test code example to make sure this works.

**Comment by 8d1h** [comment]
Sure.

**Comment by tthsqe12** [comment]
I will investigate soon.

**Comment by 8d1h** [comment]
Thanks!

**Comment by tthsqe12** [comment]
@8d1h 

@hannes14 Could you take a look at the code in the fall through case of `p_DivRem` here
https://github.com/Singular/Singular/blob/spielwiese/kernel/polys.cc#L352

There is probably something minor wrong with this code because it produces a wrong zero remainder and/or crashes even when it gets Singular's native QQ as coeffs, so I don't think this is the fault of any julia code. I tested this by removing the preceding cases which try to do the singclap division.

**Comment by hannes14** [comment]
p_DivRem fixed with https://github.com/Singular/Singular/commit/57b0db3ecf1a09223404e05d6d9a3f68940fa50f

**Pull request closed without merging**
