### PR TITLE
Add error if == is used on ideals, as the meaning is ambiguous.

### PR DESCRIPTION
**Pull request by wbhart**
Fixes https://github.com/oscar-system/Singular.jl/issues/116

### CODE REVIEW

**Comment by wbhart** [comment]
@hannes14 @raulepure @thofma 

Raul, I added you as a collaborator so you can merge patches after reviewing them.

**Comment by fieker** [comment]
On Wed, Sep 25, 2019 at 05:20:03AM -0700, wbhart wrote:
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/oscar-system/Singular.jl/pull/142
> 
> -- Commit Summary --
> 
>   * Add error if == is used on ideals, as the meaning is ambiguous.
> 
Maybe add in the error what this means? (as lists or as sets)?

**Comment by thofma** [comment]
Why is there `equal` and `isequal`?

**Comment by wbhart** [comment]
Otherwise it is ambiguous. One is mathematical comparison of ideals. The
other is Singular comparison.

**Comment by thofma** [comment]
Can we have different names? It looks pretty random that "is" changes the meaning in this way.

**Comment by wbhart** [comment]
What names do you suggest? Bear in mind that whatever you pick will upset someone.

**Comment by raulepure** [comment]
What if we do something like "equal" for the mathematical equality and "equal_generators" for the check on generators?

**Comment by thofma** [comment]
It should be clear that it is a predicate, so `isequal` and `isequal_generators` or `isequal_weak`.

**Comment by wbhart** [comment]
Fine by me. By the way @raulepure the tests current fail because your alghom's use == to test equality. This wasn't defined, so presumably the test is broken. Could you possibly do a PR to fix that so that I can rerun the tests here.

If there are no objections to isequal and isequal_generators, I will make that change today.

**Comment by thofma** [comment]
Bear in mind that `isequal` must be consistent with hashing.

**Comment by raulepure** [comment]
I fixed it in my other pull request with the change_base_ring, since I had to fix something else regarding the maps

**Comment by raulepure** [comment]
Will the command "equal" remain, or will it be replaced?

**Comment by wbhart** [comment]
isequal can't be made consistent with hashing. Two arithmetically isequal ideals may not have the same hash. Thus I suggest we find some other names. isequal is fine for comparing that the data is exactly the same, i.e. that the generators are the same. It will be consistent with hashing.

So we need another name for mathematical equality, other than isequal and ==. I suggest isset_equal. I can't imagine that causing any confusion, until Anders Isset the not so famous algebraic geometer proves the Jacobian conjecture.

**Comment by fieker** [comment]
On Thu, Sep 26, 2019 at 03:33:22AM -0700, wbhart wrote:
> isequal can't be made consistent with hashing. Two arithmetically
> isequal ideals may not have the same hash. Thus I suggest we find some
> other names. isequal is fine for comparing that the data is exactly
> the same, i.e. that the generators are the same. It will be consistent
> with hashing.
> 
> So we need another name for mathematical equality, other than isequal
> and ==. I suggest isset_equal. I can't imagine that causing any
> confusion, until Anders Isset the not so famous algebraic geometer
> proves the Jacobian conjecture.

I still think its the wrong approach. The problem is that the name is
sideal - when it is NOT an ideal. If the object is an ideal, then there
is no ambiguity at all, whatsoever about ==, there is no-where else any
other defintion other than set-equality.
Hashing, for ideals, need thus to either use a homomorphism or needs to
be based on a unique representation, aka reduced Groebner-basis.  It
sucks, but that are the options.

sideal = list of polynomials is also easy: equality is componentwise,
like any other list. Hashing also not a problem.

This is, partly, why in Oscar, sideal cannot, will not, must not be an
ideal. It is not an ideal.

In Singular.jl: do whatever you (or the singular people) want. On Oscar,
mathematics rules - even if it is inefficient.

My 2 pennies.

**Comment by wbhart** [comment]
I think there may be some confusion. We supply *both* equality of ideals and equality as lists of generators, because *both* are needed in computations. However, to prevent people accidentally shooting themselves (and others) in the foot, we do not call either ==, especially since no one agrees on what is the One True Method for comparison.

Oscar can do whatever it wants, and I personally couldn't care less what choice is made there.

It's called sideal precisely because that is what it is called in Singular and that is the convention we use throughout Singular.jl.

I very much doubt Oscar will ever use this kind of "ideal" for anything, as we've previously discussed.

**Comment by fieker** [comment]
My point is that the same structure is used in 2 different contexts, that
is the underlying error. Each context has a completely well defined
semantic, but they need to be separate. This is the mistake...

**Comment by wbhart** [comment]
And if someone creates an ideal from a list of generators in Singular.jl and then wants to compare it with ideal equality with an ideal created "mathematically"?

What you are suggesting really isn't practical. Singular ideals are NOT just used as bags to hold a list of polynomials (there is already a structure for that).

Some people make a distinction between algebraic geometry and combinatorial algebraic geometry. Only one is suitable for a computer (at least not without a fairly extensive category system).

I personally don't care about this issue one bit. If the Singular people told me to make ideal comparison hopelessly and unusably slow, and hashing just as slow, I'd do it. But people who actually want to use this package for something useful don't seem to want to do that.

**Comment by fieker** [comment]
On Thu, Sep 26, 2019 at 05:26:42AM -0700, wbhart wrote:
> And if someone creates an ideal from a list of generators in Singular.jl and then wants to compare it with ideal equality with an ideal created "mathematically"?
> 
then they get an error. You want an ideal comparison, create an ideal.
> What you are suggesting really isn't practical. Singular ideals are NOT just used as bags to hold a list of polynomials (there is already a structure for that).
> 
> Some people make a distinction between algebraic geometry and combinatorial algebraic geometry. Only one is suitable for a computer (at least not without a fairly extensive category system).
No, it's rubbish. It grew out of singular not doing mathematical
modelling properly but looking at algorithmic patterns. This does not
scale at all.
> 
> I personally don't care about this issue one bit. If the Singular
> people told me to make ideal comparison hopelessly and unusably slow,
> and hashing just as slow, I'd do it. But people who actually want to
> use this package for something useful don't seem to want to do that.

As we agree: Singular.jl: who cares.
Oscar: ideals are ideals and lists are lists. If anyone wants this
insane hybrid, they need to come up with a mathematical description and
exact specification of the operations - and a name indicating this.
S.th. like in this context I want, while in that I want s.th. different
cannot work. Furthermore, standard names need to have standard meaning
(in the sense of any non-specialist agreeing)

**Comment by wbhart** [comment]
Here is an alternative suggestion:

* we retail the existing sideal structure
* an sideal contains its GB if computed
* we annotate if it is a completely reduced, unique GB or not
* == compares ideals silently if a fully reduced, unique GB is computed for each
* if not, we return a warning, for both hash and equality
* we do not accept code in Singular.jl that results in warning messages
* we retain the existing equal function (under the name isequal_containment), for people who know what they are doing (it's faster)

This way:

* no one is under the illusion that their code is running as fast as possible when it is not
* no slowdowns are possible in library code, in either Oscar.jl or Singular.jl
* if I am not mistaken, Number Theorists stop complaining about choices made by Algebraic Geometers

**Comment by wbhart** [comment]
But I will only implement this myself if there is not future pressure to automatically compute GB's everywhere. You can see we already had people using == by mistake!!

**Comment by fingolfin** [comment]
As I see it, an `sideal` is an "ideal with generators", so it makes sense that `==` requires the generators to be equal. While `ideal` is an ideal in the mathematical sense, and so `==` should be mathematically equality, which indeed might require an expensive GB computation or even be undecidable (e.g. when one looks at ideals in more complicated non-commutative rings).

As long as there is an easy way to "convert" an `sideal` to an `ideal` or conversely, I see no issue; this should be doable efficiently in Julia with some thing "wrapper", no? The main reason we almost never do these things in GAP is because every layer of wrapping costs us there (which is why people "model" modules by matrices there, resulting in code that is fiendishly difficult to understand and debug).

**Comment by fingolfin** [comment]
So in particular, I think I agree with @fieker mostly, and I also don't see how the above would cause algebraic geometer. And if people use `==` by accident when the should not have... *shrug*.

Yet another point of view at this: `sideal` is what a computer algebraist who implements high performance algorithms uses; `ideal` is what a regular mathematician who wants to use OSCAR for research uses. (That's of course a very crude mapping, but...).

Incidentally, `sideal` to my understanding is a `singular ideal`, so I guess what I'd really want is (in C++ lingo) an abstract base class `ideal_with_generators` which then `sideal` derives from.

(And all of this could of course be phrased with category theory, but I don't think that's necessary here, although I do find it a bit helpful to understand the various correspondences, and for deciding how everything should behave in order to get a consistent overall behavior)

**Comment by fingolfin** [comment]
(and in closing, I also find it super unfortunate that there are `isequal` and `equal`. I think that will cause its fair share of issues and confusion by itself, so if one is concerned about `==` being used incorrectly, I'd apply that conern to those two as well... :-).

**Comment by wbhart** [comment]
Yours is one of two differing opinions, @fingolfin. There is no "right answer", which is why it is the way it is.

In my opinion, you are all trying to fix something that doesn't need fixing.

Chinese remaindering should clearly only operate on elements of Z/pZ, i.e. nmod's. This application to elements of Z and calling it CRT is NOT MATHEMATICAL. People who do things like that should not be writing computer algebra systems! These number theorists just don't understand the standard textbook definitions of chinese remaindering in a ring. Such a function should not be called CRT.

You see how easy this is to do! The reality is, people take this or that definition because it is computationally *useful*, not because it agrees with your favourite textbook or makes sense to a non-expert, or is what you are used to!

We just have to get over this, and move on with life. Combinatorial algebraic geometers find equality testing of ideals based on generators to be the useful concept. So much is this so that Singular does not even define the latter kind of equality in its kernel ideal interface!

But the containment equality is actually useful in test code for carefully chosen tests, which is why I implemented it. It has to have a name, but it better not be ==.

**Comment by wbhart** [comment]
@fingolfin That is *not* what @fieker is advocating. It's the exact opposite.

I am not going to continue with this discussion. It is a complete waste of my time. Someone else can sort this out. I have better things to do.

**Comment by fieker** [comment]
On Thu, Sep 26, 2019 at 06:49:49AM -0700, wbhart wrote:
> Yours is one of two differing opinions, @fingolfin. There is no "right answer", which is why it is the way it is.
> 
> In my opinion, you are all trying to fix something that doesn't need fixing.
We can stop this discussion and agree on:
no-one cares about Singular.jl. Afterall, this is a version of Singular.

However, in OSCAR, this is different. Textbook over efficiency.
Easy test-code takes a back-seat as well.
> 
> Chinese remaindering should clearly only operate on elements of Z/pZ,
> i.e. nmod's. This application to elements of Z and calling it CRT is
> NOT MATHEMATICAL. People who do things like that should not be writing
> computer algebra systems! These number theorists just don't understand
> the standard textbook definitions of chinese remaindering in a ring.
> Such a function should not be called CRT.
Why? CRT is the constuctive solution to a system of congruences - which
can be phrased as a ring isomorphism. As a ring isomorphism is applies
to pairs in Z/aZ times Z/bZ returning elements in Z/abZ.
Maybe we should defines a CRT-Map? realizing this? 
As a solver for congruences it operates on (x, a, y, b) -> z
That is a choice and well defined as well.
> 
> You see how easy this is to do! The reality is, people take this or
> that definition because it is computationally *useful*, not because it
> agrees with your favourite textbook or makes sense to a non-expert, or
> is what you are used to!
Yep, agreed.
In OSCAR, the computationally useful will have to take a back-seat over
textbook. Textbook makes things useful for non-specialists.
> 
> We just have to get over this, and move on with life. Combinatorial
> algebraic geometers find equality testing of ideals based on
> generators to be the useful concept. So much is this so that Singular
> does not even define the latter kind of equality in its kernel ideal
> interface!

Even this is not true: singular decides on a case-by-case and
function-by-functino basis if one or the other is needed. It is entirely
based on: I know what I am doing, this is efficient, thus I di it this
way.

**Comment by hannes14** [comment]
If Singular.jl is considered a version of Singular,
then equality(==) of sideal should the way Singular does it:
it is an error.
But as Singular.jl is not a version of Singular,
defined == for sideal as comparing the GB (if it is already know),
warn otherwise.

**Pull request closed without merging**
