### PR TITLE
Lift std

### PR DESCRIPTION
**Pull request by fieker**
more support for lift_std
- sideals/ smodules
- with/out syzygies
- with/out complete_reduction

needs support in libsingular_julia of course

### CODE REVIEW

**Comment by wbhart** [comment]
Tests? Documentation?

Not that any tests are passing at present, due presumably to missing stuff in libsingular_julia_jll. I personally find this separation to be unnatural. This is one case in which I strongly prefer a combined repository for Singular.jl/libsingular_julia.jll

**Comment by fieker** [comment]
On Mon, Dec 07, 2020 at 06:25:11AM -0800, wbhart wrote:
> Tests? Documentation?
Full documented! Well, as well (and better) as it was before....
(docstrings)
> 
> Not that any tests are passing at present, due presumably to missing stuff in libsingular_julia_jll. I personally find this separation to be unnatural. This is one case in which I strongly prefer a combined repository for Singular.jl/libsingular_julia.jll

Tests are tricky...., but the upstream (uncommitted for the same reason)
Oscar code runs....

**Comment by wbhart** [comment]
I mean in the documentation sources.

As for tests, I mean interface tests, just to check the code remains working, not to check Singular is returning correct answers. Without tests, the code might be removed by someone or altered in ways that break it, etc.

**Comment by fieker** [comment]
On Mon, Dec 07, 2020 at 06:43:21AM -0800, wbhart wrote:
> I mean in the documentation sources.
> 
> As for tests, I mean interface tests, just to check the code remains working, not to check Singular is returning correct answers. Without tests, the code might be removed by someone or altered in ways that break it, etc.

Yep. But no libsingular_julia, no function to test....

... and I don't think there is an obvious way to add tests for
libsingular_julia at all ...

**Comment by wbhart** [comment]
That's why there ought to be a test in Singular.jl for the correlate!

**Comment by wbhart** [comment]
The docs are in docs/src/ideal.md an module.md by the way.

**Comment by wbhart** [comment]
This can be merged as soon as the test passes, which I presume is only awaiting a new libsingular_julia.jll.

**Pull request merged**
