### PR TITLE
Reenable Nemo coefficient rings

### PR DESCRIPTION
**Pull request by wbhart**
This now passes tests. It probably still leaks some memory, but I think this functionality is better to have working and enabled, rather than bitrotting somewhere.

### CODE REVIEW

**Comment by wbhart** [comment]
@sebasguts @raulepure @steenpass

**Comment by sebasguts** [comment]
Hey, yeah, that is basically the state I ever got it to. It leaks a lot of memory. Although I am not sure it is because of missing memory handling in the interface or bugs in singular itself. Let's just merge it.

**Comment by sebasguts** [comment]
And then figure out the leaks one by one.

**Comment by wbhart** [comment]
Agreed.

Seems like the Apples are broken again.

**Pull request merged**
