### PR TITLE
use AbstractAlgebra's printing for n_unknown

### PR DESCRIPTION
**Pull request by tthsqe12**
also makes sure that canonical_unit, deepcopy_internal, and hash work.

### CODE REVIEW

**Comment by thofma** [comment]
Would be great if we could add a test.

**Comment by tthsqe12** [comment]
@thofma any thoughts on this error?

**Comment by thofma** [comment]
Not sure, I have restarted it and it seems to be working now.

Do you really want to commit the 4ti2 file?

**Comment by tthsqe12** [comment]
No - I don't know how that annoying little thing found its way in there.

**Pull request merged**
