### PR TITLE
Access caches using `get!` / `AbstractAlgebra.get_cached!`

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by tthsqe12** [comment]
Hold on. I am working on this.

**Comment by fingolfin** [comment]
@tthsqe12 you mean you are working on this PR, or on another changes touching the same file?

Anyway, if any discussion is needed, I am both on Slack and on gather right now :-)

**Comment by tthsqe12** [comment]
I am working getting my installation to a point where I can test the changes.

**Review by tthsqe12 — APPROVED** [review]
Ok. This doesn't break anything, I didn't think it would.

**Pull request merged**
