### PR TITLE
Bug fix maximal_independent_set

### PR DESCRIPTION
**Pull request by raulepure**
Fixed the output type of the resulting array.

### CODE REVIEW

**Comment by wbhart** [comment]
Is there a test we can add that will fail with the old code but not with the new code?

**Comment by raulepure** [comment]
It was just a big in the sense that the output should be of type array(spoly(elem_type(base_ring)), 1) and NOT array(spoly, 1). 
I'm not sure if this needs test code.
If it does, I will add something.

**Comment by raulepure** [comment]
I just added a test to check the right type of the resulting arrays.

**Comment by wbhart** [comment]
Thanks. I will merge once we have a green light.

**Pull request merged**
