### PR TITLE
First try on calling Singular libraries with arrays as arguments

### PR DESCRIPTION
**Pull request by raulepure**
Based on PR oscar-system/libsingular_julia#10 I tried to make the conversion of Singular.jl arrays to Singular lists work, in case the libraries are called with the ring as an argument.
I included some tests with hess.lib.

### CODE REVIEW

**Comment by tthsqe12** [comment]
@raulepure Do you get the following error message too?
```
   ? multivariate factorization over Q(alpha) depends on NTL(missing)
// ** redefining Infin (    list Infin = maxorderInfinite(f_aff);) hess.lib::RiemannRochHess:171
2-element Array{Any,1}:
 spoly{n_Q}[5*x^2*y^3-5*x*y^4-5*x^2*y^2+10*x*y^3-2*y^4-5*x*y^2+4*y^3-2*y^2, 2*x^3*y^2+x^2*y^3-3*x*y^4-2*x^3*y-x^2*y^2+6*x*y^3-3*x*y^2, 5*x^3*y^2-5*x*y^4-4*x^3*y+10*x*y^3-5*x*y^2, 5*x^4*y-5*x*y^4-x^3*y+10*x*y^3-5*x*y^2, x^5+2*x^4*y-3*x*y^4+6*x*y^3-3*x*y^2]
 x^5
```

**Comment by raulepure** [comment]
Yes indeed. This should probably be fixed on the Singular side in the near future, if some of the libraries shall be reused.
For the moment this PR is just intended to allow more input, since some Singular libraries rely on lists as an input. 
The tests I wrote here related to "hess.lib" are checked with a Singular version containing NTL.

**Comment by tthsqe12** [comment]
Ok, is the answer the same?

**Comment by raulepure** [comment]
Yes they are the same. The first test is even the same as an example in the Singular documentation for the library.

**Comment by tthsqe12** [comment]
@hannes14 We really need to get factory working without ntl. I tried calling Hecke (i.e. Julia) from c code and the resulting code looks like a nightmare to maintain and build. Therefore, I suggest getting factory working while staying completely in c. How much work is left in removing ntl? I am not talking about fixing the bugs, just converting the old code while preserving the bugs.

**Comment by hannes14** [comment]
Impllementing the missing case in factory is a lot of work,
but I will try.

**Comment by tthsqe12** [comment]
> Impllementing the missing case in factory is a lot of work,
> but I will try.

yay! I would like to help. Please let me know what I can help with.

**Comment by hannes14** [comment]
Have a look at diophantineQa in factory/facHensel, line 784.
divNTL works with Flint, but what are the transllations of the lines 864 to 872?
https://github.com/Singular/Singular/blob/spielwiese/factory/facHensel.cc#L864

**Comment by thofma** [comment]
We have new binaries with https://github.com/oscar-system/libsingular-julia/pull/10. Would be great if you could rebase.

**Comment by raulepure** [comment]
Rebase is done and tests have passed.

**Pull request merged**
