### PR TITLE
fix a bunch of constructors taking a Nemo.fmpz

### PR DESCRIPTION
**Pull request by rfourquet**
E.g. `ZZ(x::Nemo.fmpz)`.

The `flint_mpz_init_set_readonly` was called on a "Julia-managed"
`BigInt` object `a` with finalizer, but when `x` was not an
immediate integer, `a` was overwritten, which led to corruption.

### CODE REVIEW

**Comment by wbhart** [comment]
I don't understand this patch. Either Singular eats the mpz and subsequently modifies it, in which case your patch is incorrect as it will then modify the mpz underlying the fmpz, or it makes a copy of it, in which case my original code is correct.

I don't doubt that there is a crash somewhere, but I don't understand the explanation currently.

**Comment by rfourquet** [comment]
>  Either Singular eats the mpz and subsequently modifies it, in which case your patch is incorrect as it will then modify the mpz underlying the fmpz,

So to be honest, I inferred that it makes a copy by trial (testing some mutation and inspecting pointers). So I hope this makes this patch correct (but I will try to find the source in Singular to double check).

Where the previous code is incorrect is, I believe, in that it initializes `a = BigInt()` in Julia, then calls `flint_mpz_init_set_readonly`, which, as far as I understand, copies the field from `x::fmpz' which is a `BigInt` internally (when it's not an immediate integer) into `a`, and then initializes a Singular integer from `a`. I think the problem is that at one point Julia finalizes `a` which contains now a pointer to memory managed by Flint, hence the crash. I'm not 100% sure of the analysis, but it's the only explanation I could find.

**Comment by wbhart** [comment]
I think the problem is flint_mpz_init_set_readonly requires an uninitialised mpz and must be cleared with the flint function flint_mpz_clear_readonly. There should be something like a = mpz_readonly() and that should have a separate finalizer which clears the mpz using the specialised flint function.

**Comment by rfourquet** [comment]
> There should be something like a = mpz_readonly() 

Indeed; so what this patch does is similar to this: it looks into an `fmpz` a extract either an `Int` or a flint-managed `BigInt`, and feeds that to the Singular routine (no intermediate `BigInt` is created).

**Comment by wbhart** [comment]
It should be ok assuming Singular does definitely copy.

**Pull request merged**
